# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  install:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install volta
          command: |
            curl https://get.volta.sh | bash
            export VOLTA_HOME=$HOME/.volta/bin
            export PATH=$HOME/.volta/bin:$PATH
            volta install node
            volta install npm
      - run:
          name: Install dependencies
          command: |
            export PATH=$HOME/.volta/bin:$PATH
            npm i & node --version
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Lint
          command: |
            export PATH=$HOME/.volta/bin:$PATH
            npm run lint
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Test
          command: |
            export PATH=$HOME/.volta/bin:$PATH
            npm run test

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - install
      - lint
      - test
