name: Main Branch
run-name: ${{ github.actor }} is running main branch tests 🚀

on:
  push:
    branches: [main]

env:
  CI: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - id: foo
        uses: actions/test-composite-action@v1
