name: Pull Request
run-name: ${{ github.actor }} is running pull request checks 🚀

on:
  pull_request:
    types: [edited, reopened, opened, synchronize]

env:
  CI: true

jobs:
  check-pr-title:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Title of PR
        run: |
          echo '${{ github.event.pull_request.title }}' | grep -q '^\[EO-\d{1,4}\].*$'
          if [[ $? -eq 0 ]]; then
            echo "Pr title is correct"
            echo $?
          else
            echo "Incorrect PR title: should starts with [EO-XXXX] where XXXX is a task number"
            echo $?
            exit 1
          fi
