name: Pull Request
run-name: ${{ github.actor }} is running pull request checks 🚀

on:
  pull_request:
    types: [edited]

env:
  CI: true

jobs:
  check-pr-title:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Title of PR
        run: echo '${{ github.event.pull_request.title }}' | grep -E '^\[EO-\d{1,4}\].*$' || true
